---
    # todo: make rule "usable" or smth with all conveniet shit installing
    - name: setup general
      hosts: virtual
      remote_user: vagrant
      roles:
          - base

    - name: install radicale
      hosts: virtual
      remote_user: radicale
      roles:
          - radicale
