---
    # todo: make rule "usable" or smth with all conveniet shit installing
    - name: make host useable
      hosts: pi
      remote_user: ubuntu
      vars_files:
          vars.yml

      tasks:
      - name: install required programs
        apt:
            name: '{{ programs }}'
            state: present
        become: true
      - name: enable dockerd
        ansible.builtin.systemd:
            enabled: yes
            name: docker
        become: true
      - name: add user to dockergroup
        user:
            name: ubuntu
            group: docker
            state: present
        become: yes


    - name: setup radicale
      hosts: pi
      remote_user: ubuntu
      roles:
        #  - webdav
        #  - radicale
        - dyndns
