---
    # todo: make rule "usable" or smth with all conveniet shit installing
    - name: setup general
      hosts: real
      roles:
        #  - base

    - name: install radicale & setup radicale
      hosts: real
      roles:
        #  - radicale
        # - webserver
        # - reverseproxy

    - name: setup backup for radicale
      hosts: real
      roles:
          - radicale_backup
