---
  - name: Role for installing the radicale caldav-server
    debug:
        msg: start installing radicale

  - name: install pip3
    apt:
        name: python3-pip
        state: present
        update_cache: yes
    become: yes

  - name: install radicale
    pip:
        name: radicale
        state: present
        executable: pip3
    become: yes

  - name: create config folder
    ansible.builtin.file:
        path: "{{ radicale_config }}"
        owner: radicale
        state: directory
    become: yes

  - name: copy configuration file to host
    ansible.builtin.copy:
        src: config
        dest: "{{ radicale_user_config_path }}"
        owner: radicale
    become: yes

  - name: copy configuration file user home
    ansible.builtin.copy:
       src: config
       dest: "{{ radicale_config_in_home }}"
       owner: radicale
    become: yes

  - name: copy users file to host
    ansible.builtin.copy:
        src: users.secret
        dest: "{{ radicale_user_users_path }}"
        owner: radicale
        mode: '0600'
    become: yes

  - name: create collections folder
    ansible.builtin.file:
        path: "{{ radicale_collections_path }}"
        owner: radicale
        state: directory
    become: yes







  #- name: copy config file to host
#    ansible.builtin.copy:
#        src: config
#        dest:
